### ISSUE TITLE
Adding a `devcontainer.json` file for GitHub Codespaces

### ISSUE THREAD

**Issue by cr2007** [Akilan1999/p2p-rendering-computation#96]
With [GitHub Codespaces](https://github.com/features/codespaces) new being available to all users with an extremely generous monthly limit, I wanted to suggest if it is possible to create a `devcontainer` directory for easily setting up the Developer Environment.

All the packages would be installed when the codespace is setup and the developer can get into the development part straightaway.

Things required:
- [`devcontainer.json`](https://containers.dev/) - Lists all the features of the container in order to setup the required settings (extensions, libraries, image,etc.)
  - Even a Dockerfile works as well if there is an appropriate one.

**Comment by Akilan1999** [comment]
We would only want to use Github to store the repo. The fancy features are not needed.
